import { offsetToAxial } from "./hex.js";

export const COMPANY_UNIT_TEMPLATES = [
    {
      id: "c1",
      team: "company",
      name: "Mara Venn",
      epithet: "Company Captain",
      weaponId: "sword",
      hasShield: !0,
      column: 1,
      row: 2,
      hp: 76,
      headArmor: 48,
      bodyArmor: 84,
      initiative: 106,
      meleeSkill: 69,
      meleeDefense: 9,
      resolve: 62,
    },
    {
      id: "c2",
      team: "company",
      name: "Osric Vale",
      epithet: "Steady Hand",
      weaponId: "spear",
      hasShield: !0,
      column: 1,
      row: 3,
      hp: 68,
      headArmor: 36,
      bodyArmor: 72,
      initiative: 111,
      meleeSkill: 65,
      meleeDefense: 7,
      resolve: 55,
    },
    {
      id: "c3",
      team: "company",
      name: "Toman Rusk",
      epithet: "Ironbreaker",
      weaponId: "axe",
      hasShield: !1,
      column: 1,
      row: 4,
      hp: 82,
      headArmor: 52,
      bodyArmor: 88,
      initiative: 89,
      meleeSkill: 66,
      meleeDefense: 3,
      resolve: 57,
    },
    {
      id: "c4",
      team: "company",
      name: "Elia Fen",
      epithet: "Levy Veteran",
      weaponId: "mace",
      hasShield: !0,
      column: 1,
      row: 5,
      hp: 74,
      headArmor: 40,
      bodyArmor: 78,
      initiative: 94,
      meleeSkill: 64,
      meleeDefense: 8,
      resolve: 52,
    },
    {
      id: "c5",
      team: "company",
      name: "Bram Coal",
      epithet: "Pit Fighter",
      weaponId: "axe",
      hasShield: !1,
      column: 1,
      row: 6,
      hp: 88,
      headArmor: 28,
      bodyArmor: 66,
      initiative: 96,
      meleeSkill: 68,
      meleeDefense: 2,
      resolve: 59,
    },
    {
      id: "c6",
      team: "company",
      name: "Iven Pike",
      epithet: "Young Spear",
      weaponId: "spear",
      hasShield: !0,
      column: 1,
      row: 7,
      hp: 65,
      headArmor: 32,
      bodyArmor: 68,
      initiative: 116,
      meleeSkill: 63,
      meleeDefense: 6,
      resolve: 48,
    },
  ],
  ENEMY_UNIT_TEMPLATES = [
    {
      id: "e1",
      team: "enemy",
      name: "Harl Kest",
      epithet: "Raid Captain",
      weaponId: "sword",
      hasShield: !0,
      column: 10,
      row: 2,
      hp: 75,
      headArmor: 44,
      bodyArmor: 82,
      initiative: 104,
      meleeSkill: 67,
      meleeDefense: 8,
      resolve: 60,
    },
    {
      id: "e2",
      team: "enemy",
      name: "Cutter",
      epithet: "Thorn Reaver",
      weaponId: "axe",
      hasShield: !1,
      column: 10,
      row: 3,
      hp: 80,
      headArmor: 38,
      bodyArmor: 76,
      initiative: 92,
      meleeSkill: 66,
      meleeDefense: 3,
      resolve: 53,
    },
    {
      id: "e3",
      team: "enemy",
      name: "Wolfe",
      epithet: "Road Spear",
      weaponId: "spear",
      hasShield: !0,
      column: 10,
      row: 4,
      hp: 66,
      headArmor: 34,
      bodyArmor: 70,
      initiative: 110,
      meleeSkill: 64,
      meleeDefense: 7,
      resolve: 50,
    },
    {
      id: "e4",
      team: "enemy",
      name: "Moll Ash",
      epithet: "Bone Knocker",
      weaponId: "mace",
      hasShield: !0,
      column: 10,
      row: 5,
      hp: 72,
      headArmor: 42,
      bodyArmor: 80,
      initiative: 95,
      meleeSkill: 64,
      meleeDefense: 7,
      resolve: 54,
    },
    {
      id: "e5",
      team: "enemy",
      name: "Red Senn",
      epithet: "Oathless",
      weaponId: "sword",
      hasShield: !1,
      column: 10,
      row: 6,
      hp: 71,
      headArmor: 30,
      bodyArmor: 64,
      initiative: 112,
      meleeSkill: 65,
      meleeDefense: 4,
      resolve: 49,
    },
    {
      id: "e6",
      team: "enemy",
      name: "Garran",
      epithet: "Gate Axe",
      weaponId: "axe",
      hasShield: !1,
      column: 10,
      row: 7,
      hp: 84,
      headArmor: 50,
      bodyArmor: 86,
      initiative: 87,
      meleeSkill: 67,
      meleeDefense: 2,
      resolve: 58,
    },
  ],
  ENEMY_FACTIONS = {
    "thorn-reavers": [
      { name: "Harl Kest", epithet: "Thorn Captain" },
      { name: "Cutter", epithet: "Thorn Reaver" },
      { name: "Wolfe", epithet: "Road Spear" },
      { name: "Moll Ash", epithet: "Bone Knocker" },
      { name: "Red Senn", epithet: "Oathless" },
      { name: "Garran", epithet: "Gate Axe" },
    ],
    mireborn: [
      {
        name: "Vey Fen",
        epithet: "Mire Caller",
        weaponId: "spear",
        hasShield: !1,
      },
      {
        name: "Lark",
        epithet: "Bog Runner",
        weaponId: "sword",
        hasShield: !1,
      },
      {
        name: "Moss",
        epithet: "Reed Spear",
        weaponId: "spear",
        hasShield: !1,
      },
      {
        name: "Old Nymm",
        epithet: "Drowner",
        weaponId: "mace",
        hasShield: !1,
      },
      {
        name: "Sedge",
        epithet: "Fen Knife",
        weaponId: "sword",
        hasShield: !1,
      },
      { name: "Hurn", epithet: "Marsh Axe", weaponId: "axe", hasShield: !1 },
    ],
    ironbound: [
      {
        name: "Ser Krail",
        epithet: "Ironbound Marshal",
        weaponId: "mace",
        hasShield: !0,
      },
      { name: "Dorr", epithet: "Plate Axe", weaponId: "axe", hasShield: !0 },
      {
        name: "Halvek",
        epithet: "Wall Spear",
        weaponId: "spear",
        hasShield: !0,
      },
      {
        name: "Brin",
        epithet: "Chain Bearer",
        weaponId: "mace",
        hasShield: !0,
      },
      {
        name: "Kerr",
        epithet: "Black Sword",
        weaponId: "sword",
        hasShield: !0,
      },
      {
        name: "Voss",
        epithet: "Gate Hammer",
        weaponId: "mace",
        hasShield: !1,
      },
    ],
  };
export function createUnit(s) {
  return {
    id: s.id,
    team: s.team,
    name: s.name,
    epithet: s.epithet,
    weaponId: s.weaponId,
    hasShield: s.hasShield,
    position: offsetToAxial(s.column, s.row),
    hp: s.hp,
    hpMax: s.hp,
    headArmor: s.headArmor,
    headArmorMax: s.headArmor,
    bodyArmor: s.bodyArmor,
    bodyArmorMax: s.bodyArmor,
    fatigue: 0,
    fatigueMax: 100,
    ap: 9,
    apMax: 9,
    initiative: s.initiative,
    meleeSkill: s.meleeSkill,
    meleeDefense: s.meleeDefense,
    resolve: s.resolve,
    morale: "steady",
    alive: !0,
    routed: !1,
    waited: !1,
    movedThisTurn: !1,
    kills: 0,
  };
}
