export const WEAPONS = {
    sword: {
      id: "sword",
      name: "Arming sword",
      verb: "Slash",
      icon: "†",
      damageMin: 34,
      damageMax: 44,
      armorMultiplier: 0.72,
      penetration: 0.22,
      accuracy: 10,
      apCost: 4,
      fatigueCost: 12,
      description: "Reliable and quick. Strong against exposed flesh.",
    },
    spear: {
      id: "spear",
      name: "Boar spear",
      verb: "Thrust",
      icon: "↟",
      damageMin: 28,
      damageMax: 38,
      armorMultiplier: 0.65,
      penetration: 0.3,
      accuracy: 18,
      apCost: 4,
      fatigueCost: 14,
      description: "Accurate and disciplined. Punches through weak points.",
    },
    axe: {
      id: "axe",
      name: "Bearded axe",
      verb: "Hack",
      icon: "⌁",
      damageMin: 39,
      damageMax: 52,
      armorMultiplier: 1.35,
      penetration: 0.18,
      accuracy: 0,
      apCost: 5,
      fatigueCost: 18,
      description: "Tears shields and armor apart at a heavy cost.",
    },
    mace: {
      id: "mace",
      name: "Iron mace",
      verb: "Crush",
      icon: "●",
      damageMin: 31,
      damageMax: 42,
      armorMultiplier: 1.05,
      penetration: 0.34,
      accuracy: -4,
      apCost: 5,
      fatigueCost: 20,
      description: "Concussive blows exhaust and unsettle the target.",
      effect: "stagger",
    },
  },
  TERRAIN = {
    grass: { name: "Dry grass", moveCost: 2, defense: 0, color: "#5f6344" },
    road: { name: "Old road", moveCost: 1, defense: 0, color: "#76664d" },
    brush: { name: "Thorn brush", moveCost: 3, defense: 5, color: "#46503a" },
    mud: { name: "Churned mud", moveCost: 3, defense: -3, color: "#4c4134" },
    water: {
      name: "Shallow water",
      moveCost: 4,
      defense: -5,
      color: "#40565a",
    },
    rock: { name: "Boulder", moveCost: 99, defense: 0, color: "#4a4d4a" },
    hill: { name: "High ground", moveCost: 3, defense: 3, color: "#737052" },
  },
  MORALE_LADDER = ["fleeing", "breaking", "wavering", "steady", "confident"];
export function moraleIndex(s) {
  return MORALE_LADDER.indexOf(s);
}
export function weakenMorale(s) {
  return MORALE_LADDER[Math.max(0, moraleIndex(s) - 1)] ?? "fleeing";
}
