export const ORIGINS = {
    "road-wardens": {
      name: "Broken Wardens",
      description:
        "A dismissed border patrol with discipline, shields, and enemies in every tollhouse.",
      effect: "+2 shields · stronger starting armor",
    },
    "caravan-guard": {
      name: "Caravan Remnant",
      description:
        "Guards from a merchant train that never reached the coast. Coin remains, loyalty less so.",
      effect: "+250 crowns · +3 tools",
    },
    oathless: {
      name: "The Oathless",
      description:
        "Deserters bound by mutual guilt. Harder to frighten, harder to employ cheaply.",
      effect: "+4 resolve · higher wages",
    },
  },
  STARTING_FIGHTERS = [
    {
      name: "Mara Venn",
      epithet: "Company Captain",
      background: "Disgraced Sergeant",
      hp: 76,
      hpMax: 76,
      headArmor: 48,
      headArmorMax: 48,
      bodyArmor: 84,
      bodyArmorMax: 84,
      initiative: 106,
      meleeSkill: 69,
      meleeDefense: 9,
      resolve: 62,
      weaponId: "sword",
      hasShield: !0,
      wage: 19,
    },
    {
      name: "Osric Vale",
      epithet: "Steady Hand",
      background: "Militia Veteran",
      hp: 68,
      hpMax: 68,
      headArmor: 36,
      headArmorMax: 36,
      bodyArmor: 72,
      bodyArmorMax: 72,
      initiative: 111,
      meleeSkill: 65,
      meleeDefense: 7,
      resolve: 55,
      weaponId: "spear",
      hasShield: !0,
      wage: 15,
    },
    {
      name: "Toman Rusk",
      epithet: "Ironbreaker",
      background: "Mine Guard",
      hp: 82,
      hpMax: 82,
      headArmor: 52,
      headArmorMax: 52,
      bodyArmor: 88,
      bodyArmorMax: 88,
      initiative: 89,
      meleeSkill: 66,
      meleeDefense: 3,
      resolve: 57,
      weaponId: "axe",
      hasShield: !1,
      wage: 17,
    },
    {
      name: "Elia Fen",
      epithet: "Levy Veteran",
      background: "Farmhand",
      hp: 74,
      hpMax: 74,
      headArmor: 40,
      headArmorMax: 40,
      bodyArmor: 78,
      bodyArmorMax: 78,
      initiative: 94,
      meleeSkill: 64,
      meleeDefense: 8,
      resolve: 52,
      weaponId: "mace",
      hasShield: !0,
      wage: 14,
    },
    {
      name: "Bram Coal",
      epithet: "Pit Fighter",
      background: "Charcoal Burner",
      hp: 88,
      hpMax: 88,
      headArmor: 28,
      headArmorMax: 28,
      bodyArmor: 66,
      bodyArmorMax: 66,
      initiative: 96,
      meleeSkill: 68,
      meleeDefense: 2,
      resolve: 59,
      weaponId: "axe",
      hasShield: !1,
      wage: 16,
    },
    {
      name: "Iven Pike",
      epithet: "Young Spear",
      background: "Fisher's Son",
      hp: 65,
      hpMax: 65,
      headArmor: 32,
      headArmorMax: 32,
      bodyArmor: 68,
      bodyArmorMax: 68,
      initiative: 116,
      meleeSkill: 63,
      meleeDefense: 6,
      resolve: 48,
      weaponId: "spear",
      hasShield: !0,
      wage: 12,
    },
    {
      name: "Nell Quill",
      epithet: "Quiet Knife",
      background: "Poacher",
      hp: 63,
      hpMax: 63,
      headArmor: 24,
      headArmorMax: 24,
      bodyArmor: 58,
      bodyArmorMax: 58,
      initiative: 121,
      meleeSkill: 66,
      meleeDefense: 5,
      resolve: 51,
      weaponId: "sword",
      hasShield: !1,
      wage: 13,
    },
    {
      name: "Jory Hask",
      epithet: "Wall Born",
      background: "Mason",
      hp: 84,
      hpMax: 84,
      headArmor: 44,
      headArmorMax: 44,
      bodyArmor: 82,
      bodyArmorMax: 82,
      initiative: 86,
      meleeSkill: 62,
      meleeDefense: 8,
      resolve: 61,
      weaponId: "mace",
      hasShield: !0,
      wage: 15,
    },
  ],
  RECRUIT_POOL = [
    ["Ansel Reed", "Marsh Guide", "Rat Catcher"],
    ["Ketta Morn", "Hard Bargain", "Butcher"],
    ["Rulf Tanner", "Old Hide", "Tanner"],
    ["Sella Grey", "Long Memory", "Gravedigger"],
    ["Dain Hollow", "No Banner", "Deserter"],
    ["Merrit Fox", "Quick Hands", "Thief"],
  ],
  LOCATIONS = {
    cinderfall: {
      id: "cinderfall",
      name: "Cinderfall",
      subtitle: "Free-town of smoke and ledgers",
      description:
        "A market town built where three toll roads meet beneath black chimneys.",
      x: 15,
      y: 55,
      neighbors: ["fenmere", "cael-watch"],
      terrainVariant: "cinder-streets",
      reputation: "free-towns",
      services: ["contracts", "market", "recruits", "healer"],
    },
    fenmere: {
      id: "fenmere",
      name: "Fenmere",
      subtitle: "Reed roofs above black water",
      description:
        "The Fenwardens keep narrow causeways open with poles, bells and old grudges.",
      x: 31,
      y: 78,
      neighbors: ["cinderfall", "blackbriar"],
      terrainVariant: "fen-crossing",
      reputation: "fenwardens",
      services: ["contracts", "market", "recruits"],
    },
    "cael-watch": {
      id: "cael-watch",
      name: "Cael Watch",
      subtitle: "A crumbling noble border post",
      description:
        "House Cael's faded banners still fly above the frontier's last stone tower.",
      x: 37,
      y: 31,
      neighbors: ["cinderfall", "red-quarry", "blackbriar"],
      terrainVariant: "old-watch",
      reputation: "house-cael",
      services: ["contracts", "market", "healer"],
    },
    blackbriar: {
      id: "blackbriar",
      name: "Blackbriar",
      subtitle: "The road swallowed by thorns",
      description:
        "No charter holds here. Tracks vanish overnight and the marsh speaks after dark.",
      x: 54,
      y: 65,
      neighbors: ["fenmere", "cael-watch", "iron-pass"],
      terrainVariant: "blackbriar",
      reputation: "fenwardens",
      services: ["contracts", "recruits"],
    },
    "red-quarry": {
      id: "red-quarry",
      name: "Red Quarry",
      subtitle: "Iron cut from a wounded hill",
      description:
        "Miners and debtors work beneath cranes that never stop creaking.",
      x: 61,
      y: 27,
      neighbors: ["cael-watch", "iron-pass"],
      terrainVariant: "quarry-pit",
      reputation: "house-cael",
      services: ["contracts", "market", "recruits"],
    },
    "iron-pass": {
      id: "iron-pass",
      name: "Iron Pass",
      subtitle: "The frontier's narrow throat",
      description:
        "All eastern roads converge between cliffs where the Ironbound levy gathers.",
      x: 73,
      y: 45,
      neighbors: ["blackbriar", "red-quarry", "crowns-end"],
      terrainVariant: "iron-pass",
      reputation: "free-towns",
      services: ["contracts", "market"],
    },
    "crowns-end": {
      id: "crowns-end",
      name: "Crown's End",
      subtitle: "A fortress without a king",
      description:
        "The old frontier fortress commands every road west. Its final toll is paid in blood.",
      x: 88,
      y: 69,
      neighbors: ["iron-pass"],
      terrainVariant: "iron-pass",
      reputation: "free-towns",
      services: ["contracts"],
    },
  },
  CONTRACTS = [
    {
      title: "The Ash Road Levy",
      employer: "Cinderfall Council",
      briefing:
        "Road-thieves have taken a season's tithe. Bring back the iron and open the west road.",
      objective: "Break the Thorn Reavers",
      terrainLabel: "Old road · central rise",
      terrainVariant: "ash-road",
      locationId: "cinderfall",
      reputation: "free-towns",
      enemyFaction: "thorn-reavers",
      battleObjective: "eliminate",
      reputationReward: 3,
      threatChange: -4,
      baseDanger: 1,
      baseReward: 390,
    },
    {
      title: "Smoke Between Houses",
      employer: "The Lamp Guild",
      briefing:
        "Raiders entered Cinderfall behind a charcoal wagon. Hold the square until the watch rallies.",
      objective: "Hold the market square for two rounds",
      terrainLabel: "Streets · barricades · square",
      terrainVariant: "cinder-streets",
      locationId: "cinderfall",
      reputation: "free-towns",
      enemyFaction: "thorn-reavers",
      battleObjective: "hold",
      objectiveRounds: 2,
      reputationReward: 4,
      threatChange: -5,
      baseDanger: 2,
      baseReward: 520,
    },
    {
      title: "Black Water Crossing",
      employer: "The Fenwardens",
      briefing:
        "Mireborn deserters tax the flooded ford. Make the crossing belong to Fenmere again.",
      objective: "Clear the flooded crossing",
      terrainLabel: "Mud · water · poor footing",
      terrainVariant: "fen-crossing",
      locationId: "fenmere",
      reputation: "fenwardens",
      enemyFaction: "mireborn",
      battleObjective: "eliminate",
      reputationReward: 3,
      threatChange: -4,
      baseDanger: 1,
      baseReward: 420,
    },
    {
      title: "Six Rounds of Rain",
      employer: "Reed-Mother Yara",
      briefing:
        "Families are crossing behind you. Stand in the flood until every punt reaches Fenmere.",
      objective: "Survive six rounds",
      terrainLabel: "Floodwater · reeds · causeway",
      terrainVariant: "fen-crossing",
      locationId: "fenmere",
      reputation: "fenwardens",
      enemyFaction: "mireborn",
      battleObjective: "survive",
      objectiveRounds: 6,
      reputationReward: 5,
      threatChange: -6,
      baseDanger: 2,
      baseReward: 580,
    },
    {
      title: "Watchfires at Dusk",
      employer: "House Cael's Bailiff",
      briefing:
        "Raiders have occupied the old watch. Take the high ground before their signal fires are lit.",
      objective: "Hold the watch platform",
      terrainLabel: "High ground · brush · rock",
      terrainVariant: "old-watch",
      locationId: "cael-watch",
      reputation: "house-cael",
      enemyFaction: "thorn-reavers",
      battleObjective: "hold",
      objectiveRounds: 2,
      reputationReward: 4,
      threatChange: -5,
      baseDanger: 2,
      baseReward: 560,
    },
    {
      title: "The Bailiff's Writ",
      employer: "House Cael",
      briefing:
        "An Ironbound marshal has hanged three tax riders. Kill the marshal; the levy will lose its nerve.",
      objective: "Break the enemy captain",
      terrainLabel: "Watch ruins · steep ground",
      terrainVariant: "old-watch",
      locationId: "cael-watch",
      reputation: "house-cael",
      enemyFaction: "ironbound",
      battleObjective: "break-captain",
      reputationReward: 5,
      threatChange: -6,
      baseDanger: 3,
      baseReward: 720,
    },
    {
      title: "Thorns Have Teeth",
      employer: "Fenmere Trackers",
      briefing:
        "The Mireborn circle through Blackbriar. Three fighters must carry the warning east.",
      objective: "Escape three fighters across the eastern edge",
      terrainLabel: "Dense thorns · black pools",
      terrainVariant: "blackbriar",
      locationId: "blackbriar",
      reputation: "fenwardens",
      enemyFaction: "mireborn",
      battleObjective: "escape",
      reputationReward: 4,
      threatChange: -4,
      baseDanger: 2,
      baseReward: 500,
    },
    {
      title: "A Bell Under Roots",
      employer: "The Briar Hermit",
      briefing:
        "A Thorn captain rings an old levy bell beneath the trees. Silence the captain before help arrives.",
      objective: "Break the enemy captain",
      terrainLabel: "Briar lanes · drowned stones",
      terrainVariant: "blackbriar",
      locationId: "blackbriar",
      reputation: "free-towns",
      enemyFaction: "thorn-reavers",
      battleObjective: "break-captain",
      reputationReward: 4,
      threatChange: -5,
      baseDanger: 2,
      baseReward: 590,
    },
    {
      title: "Debt in Red Stone",
      employer: "Quarry Syndics",
      briefing:
        "The Ironbound have chained the lifts and taken the powder store. Clear the quarry floor.",
      objective: "Break the Ironbound line",
      terrainLabel: "Quarry ledges · flooded pit",
      terrainVariant: "quarry-pit",
      locationId: "red-quarry",
      reputation: "house-cael",
      enemyFaction: "ironbound",
      battleObjective: "eliminate",
      reputationReward: 5,
      threatChange: -6,
      baseDanger: 3,
      baseReward: 760,
    },
    {
      title: "The Last Lift",
      employer: "Free Miners",
      briefing:
        "Hold the loading platform while the last families ride the quarry lift to safety.",
      objective: "Hold the lift platform",
      terrainLabel: "Stone shelves · machinery",
      terrainVariant: "quarry-pit",
      locationId: "red-quarry",
      reputation: "free-towns",
      enemyFaction: "ironbound",
      battleObjective: "hold",
      objectiveRounds: 2,
      reputationReward: 5,
      threatChange: -6,
      baseDanger: 3,
      baseReward: 790,
    },
    {
      title: "The Narrow Toll",
      employer: "Frontier Compact",
      briefing:
        "The Ironbound close the pass by sunset. Break their marshal and open the road to Crown's End.",
      objective: "Break the pass marshal",
      terrainLabel: "Cliffs · narrow road · high ground",
      terrainVariant: "iron-pass",
      locationId: "iron-pass",
      reputation: "free-towns",
      enemyFaction: "ironbound",
      battleObjective: "break-captain",
      reputationReward: 6,
      threatChange: -8,
      baseDanger: 3,
      baseReward: 900,
    },
    {
      title: "The Iron Price",
      employer: "The Frontier Compact",
      briefing:
        "Every toll, grave and broken oath leads here. Take Crown's End and end the Ironbound claim.",
      objective: "Break the final Ironbound company",
      terrainLabel: "Fortress road · killing ground",
      terrainVariant: "iron-pass",
      locationId: "crowns-end",
      reputation: "free-towns",
      enemyFaction: "ironbound",
      battleObjective: "eliminate",
      reputationReward: 10,
      threatChange: -100,
      story: "final",
      baseDanger: 3,
      baseReward: 1400,
    },
  ];
export const ROAD_EVENTS = [
  {
    id: "broken-cart",
    title: "A Cart in the Rain",
    body: "A merchant's axle has split where the road sinks into mud. His guards watch your tools more closely than the tree line.",
    illustration: "road",
    choices: [
      {
        id: "help",
        label: "Lend tools",
        detail: "Spend 1 tool; gain Free-town reputation and food.",
      },
      {
        id: "charge",
        label: "Name a price",
        detail: "Gain crowns; the road remembers.",
      },
    ],
  },
  {
    id: "old-fire",
    title: "Someone Else's Fire",
    body: "A deserted camp still burns. Bedrolls lie open and a sealed medicine case rests beside the coals.",
    illustration: "camp",
    choices: [
      {
        id: "take",
        label: "Take the case",
        detail: "Gain medicine; increase frontier threat.",
      },
      {
        id: "wait",
        label: "Wait for the owners",
        detail: "Lose time; gain renown and reputation.",
      },
    ],
  },
  {
    id: "stone-oath",
    title: "Names Cut in Stone",
    body: "At a ruined milepost, old company names have been cut deep enough to survive the kingdom that hired them.",
    illustration: "ruin",
    choices: [
      {
        id: "carve",
        label: "Add your company",
        detail: "Gain resolve and renown; spend a day.",
      },
      { id: "pass", label: "Keep moving", detail: "No cost. No promise." },
    ],
  },
  {
    id: "black-storm",
    title: "The Black Storm",
    body: "Ash-dark clouds roll out of the pass. The road disappears under rain and frightened horses pull at their traces.",
    illustration: "storm",
    choices: [
      {
        id: "shelter",
        label: "Make a hard camp",
        detail: "Spend food and a day; preserve the company.",
      },
      {
        id: "push",
        label: "Push through",
        detail: "Arrive sooner; several fighters take damage.",
      },
    ],
  },
];
export const PERKS = {
  vanguard: {
    name: "Vanguard",
    description: "+3 melee skill and +5 initiative.",
  },
  bulwark: {
    name: "Bulwark",
    description: "+2 defence and reinforced armor.",
  },
  slayer: {
    name: "Slayer",
    description: "+2 skill and improved weapon handling.",
  },
  steadfast: { name: "Steadfast", description: "+6 resolve." },
  pathfinder: {
    name: "Pathfinder",
    description: "+10 initiative and +4 health.",
  },
  quartermaster: {
    name: "Quartermaster",
    description: "Reduce daily wage by 3 crowns.",
  },
};
export const INJURIES = [
  "Cracked ribs",
  "Split brow",
  "Wrenched shoulder",
  "Deep bruising",
  "Shaken nerve",
  "Gasher's scar",
];
